name: Push to Replicate

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push_to_replicate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}
      - name: Push to Replicate
        run: cog push r/wetson3234/text-generator-cog
